[package]
name = "ray-dashboard-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
progenitor-client = "0.11.2"
reqwest = "0.12.24"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"

[dev-dependencies]
once_cell = "1.21.3"
tokio = { version = "1.48.0", features = ["full"] }
