services:
  ray:
    image: rayproject/ray:2.50.1
    container_name: ray
    command: >
      bash -c "
      ray start --head --dashboard-host=0.0.0.0 --dashboard-port=8265 --block
      "
    ports:
      - "8265:8265" # Ray dashboard
      - "8000:8000" # Ray Serve HTTP endpoint
